### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by EderSantana** [Clarifai/clarifai-nodejs#3]
Hi,

I installed everything, registered on the website and ran `node clarifai_sample.js 1 1 -v`. But I got the following results
```
using CLIENT_ID=__myid__, CLIENT_SECRET=__mysecret__
Server refused request due to invalid Access Token
Requesting new Access Token. Queuing request for completion with fresh token.
Server refused request due to invalid Access Token
Access Token request already in flight. Queuing request for completion with fresh token.
Server refused request due to invalid Access Token
Access Token request already in flight. Queuing request for completion with fresh token.
Server refused request due to invalid Access Token
Access Token request already in flight. Queuing request for completion with fresh token.
```
The python example gave a different result that looked correct. Am I missing something here?

**Comment by jimreesman** [comment]
try `node clarifai_sample.js --print-results`. by default, the node client takes care of automatically getting/refreshing the access token on your behalf. the `-v` option causes messages to be shown for the first time that requests cause a token to be requested. but then, because you haven't included `--print-results`, you're not seeing the successful returns from the requests that are automatically retried once a token is received. (i'm assuming `__myid__` and `__mysecret__` are placeholders for your id/secret ... )

**Comment by EderSantana** [comment]
Oh, I see. I didn't pay attention to the -- flag, I went straight to the code and tried to make sense of it myself. Anyway, thanks for the fast reply. It is working.
